### ISSUE TITLE
Problema al crear usuarios : mas de un rol

### ISSUE THREAD

**Issue by JulianAlconcher** [totoccar/Hospitales2000#30]
Por ejemplo: 
Si creo un paciente con dni 12345678 --> Se crea bien
Luego, creo un MEDICO con el mismo dni (12345678) --> FALLA, ya que DNI es "@unique" en la tabla usuarios (creo). 

Este mismo problema se repite para cualquier usuario que ya tenga un rol en el sistema. 

Hay que arreglar que ese nuevo medico se sume a la relacion USUARIO-->MEDICO y que lo asocie al mismo dni y mismo user_id. 

![image](https://github.com/user-attachments/assets/32654bc2-cd34-4574-a2c1-6e93311b6a7e)

**Comment by totoccar** [comment]
Genial. Buena observacion.
